server:
  port: 8080

spring:
  liquibase:
    enabled: true
    drop-first: true
    default-schema: public
    change-log: classpath:db/changelog_init.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgresql
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        show_sql: false
        hbm2ddl:
          auto: none

foreign-currency-market:
  api:
    getCurrencies: https://www.cbr-xml-daily.ru/daily_utf8.xml

